version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=production
    ports: 
      - "9095:3000" 
    networks:
      - skeleton  
    depends_on:
      - mongo
    volumes:
      - media:/media/
  mongo: 
    image: mongo
    ports:
      - "27017:27017" 
    volumes:
      - database:/data
    networks:
      - skeleton     
volumes:
  database:
  media:
networks: 
  skeleton: